### ISSUE TITLE
SqsActiveJob doesn't need Rails

### ISSUE THREAD

**Issue by ckhsponge** [aws/aws-activejob-sqs-ruby#5]
Thanks for creating SqsActiveJob! I've tested it and it seems to work well.

My feature request is to split SqsActiveJob into it's own gem and remove the dependency on Rails. The ActiveJob gem does not require Rails. Lambdas can run Ruby. A lightweight Lambda could have a few gems not including Rails and be very effective at background job processing.

I've tested the project after removing 3 Rails references:

1. Logger - A Rails logger is used. To fix this, check if Rails exists. If not, then use the standard Logger instead of the Rails logger.
2. Config - A configuration file existence is checked in the Rails root. Don't look for this file if Rails doesn't exist.
3. Polling - The Rails environment is loaded before polling. Don't do this. Instead start whatever environment is appropriate and then initiate polling.

I'd be happy to split this project out myself however not maintaining it in 2 places would be better.

**Comment by alextwoods** [comment]
This feature has been released as part of aws-activejob-1.0 - you can now run without rails! (See the readme for details).  Thanks for suggesting this!
