### ISSUE TITLE
Connect with RubyGems Better

### ISSUE THREAD

**Issue by ssunday** [aws/aws-activejob-sqs-ruby#8]
https://rubygems.org/gems/aws-activejob-sqs link to github

also the 'Gem Version' badge fury thing doesn't link properly 

I think this is the case with all the new split up gems 😅

**Comment by mullermp** [comment]
Thanks, I'll take a look. I set the homepage in the gemspec. Is that what you're referring to?

**Comment by mullermp** [comment]
I've fixed them for 4 of the gems, but for some reason aws-record-rails has the correct link and doesn't have a version? The homepage is set on all of the gems - I'm stumped on that one.

**Comment by ssunday** [comment]
I don't see the homepage yet on ruby gems but I'm wondering if it requires another release. 

Yeah, just a way to go from gem -> source code. Changelog is also possible, IIRC, but not necessary.

**Comment by mullermp** [comment]
Reached out to the RubyGems people, it's a bug on their side. https://github.com/rubygems/rubygems.org/pull/5249
